- name: install nginx
  hosts: local
  connection: local # Ansible is connecting to localhost
  become: true
  tasks:
   - name: install nginx
     ansible.builtin.yum:
      name: nginx
      state: present
   - name: start nginx
     ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: true