- name : variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: user login name
    private: false
  - name: password
    prompt: user login password
    private: true
  tasks:
  - name: print the username
    ansible.builtin.debug:
      msg: "Username is {{ username }}"

