- name : veriabls fom promt
  hosts: local
  conncetion: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false
  tasks:
  - name: print the username
    ansible.builtin.debug:
      msg: "Username is {{ username }}"

