- name: variable in file
  host: local
  connection: local
  -tasks:
    - name: print course info
      ansible.builtin.debug:
        msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"