- name: Veriable form Aurgs
  hosts: localhost
  connection: local
  tasks:
    - name: print course info
      ansible.builtin.debug:
        msg: "Course name is {{ coursename }}, Duration is {{ duration }}, price is {{ price }}"